import { Client } from "../client/client.ts"
import CHANNEL_CREATE from "./CHANNEL_CREATE.ts"
import CHANNEL_DELETE from "./CHANNEL_DELETE.ts"
import CHANNEL_UPDATE from "./CHANNEL_UPDATE.ts"
import GUILD_CREATE from "./GUILD_CREATE.ts"
import GUILD_DELETE from "./GUILD_DELETE.ts"
import GUILD_ROLE_CREATE from "./GUILD_ROLE_CREATE.ts"
import GUILD_ROLE_DELETE from "./GUILD_ROLE_DELETE.ts"
import GUILD_ROLE_UPDATE from "./GUILD_ROLE_UPDATE.ts"
import MESSAGE_CREATE from "./MESSAGE_CREATE.ts"
import MESSAGE_DELETE from "./MESSAGE_DELETE.ts"
import MESSAGE_REACTION_ADD from "./MESSAGE_REACTION_ADD.ts"
import MESSAGE_REACTION_REMOVE from "./MESSAGE_REACTION_REMOVE.ts"
import MESSAGE_REACTION_REMOVE_ALL from "./MESSAGE_REACTION_REMOVE_ALL.ts"
import MESSAGE_UPDATE from "./MESSAGE_UPDATE.ts"
import TYPING_START from "./TYPING_START.ts"
import GUILD_BAN_ADD from "./GUILD_BAN_ADD.ts"
import GUILD_BAN_REMOVE from "./GUILD_BAN_REMOVE.ts"
import MESSAGE_DELETE_BULK from "./MESSAGE_DELETE_BULK.ts"
import INVITE_CREATE from "./INVITE_CREATE.ts"
import INVITE_DELETE from "./INVITE_DELETE.ts"
import GUILD_MEMBER_ADD from "./GUILD_MEMBER_ADD.ts"
import GUILD_MEMBER_REMOVE from "./GUILD_MEMBER_REMOVE.ts"
import GUILD_MEMBER_UPDATE from "./GUILD_MEMBER_UPDATE.ts"
import CHANNEL_PINS_UPDATE from "./CHANNEL_PINS_UPDATE.ts"
import PRESENCE_UPDATE from "./PRESENCE_UPDATE.ts"
import GUILD_MEMBERS_CHUNK from "./GUILD_MEMBERS_CHUNK.ts"
import VOICE_SERVER_UPDATE from "./VOICE_SERVER_UPDATE.ts"
import VOICE_STATE_UPDATE from "./VOICE_STATE_UPDATE.ts"
import INTERACTION_CREATE from "./INTERACTION_CREATE.ts"
import APPLICATION_COMMAND_CREATE from "./APPLICATION_COMMAND_CREATE.ts"
import APPLICATION_COMMAND_DELETE from "./APPLICATION_COMMAND_DELETE.ts"
import APPLICATION_COMMAND_UPDATE from "./APPLICATION_COMMAND_UPDATE.ts"
import { DictionaryType } from "../../mod.ts"

const intents: DictionaryType = {
    CHANNEL_CREATE,
    CHANNEL_DELETE,
    CHANNEL_UPDATE,
    GUILD_CREATE,
    GUILD_DELETE,
    GUILD_ROLE_CREATE,
    GUILD_ROLE_DELETE,
    GUILD_ROLE_UPDATE,
    MESSAGE_CREATE,
    MESSAGE_UPDATE,
    MESSAGE_DELETE,
    MESSAGE_REACTION_ADD,
    MESSAGE_REACTION_REMOVE,
    MESSAGE_REACTION_REMOVE_ALL,
    TYPING_START,
    GUILD_BAN_ADD,
    GUILD_BAN_REMOVE,
    MESSAGE_DELETE_BULK,
    INVITE_CREATE,
    INVITE_DELETE,
    GUILD_MEMBER_ADD,
    GUILD_MEMBER_REMOVE,
    GUILD_MEMBER_UPDATE,
    CHANNEL_PINS_UPDATE,
    PRESENCE_UPDATE,
    GUILD_MEMBERS_CHUNK,
    VOICE_SERVER_UPDATE,
    VOICE_STATE_UPDATE,
    INTERACTION_CREATE,
    APPLICATION_COMMAND_CREATE,
    APPLICATION_COMMAND_DELETE,
    APPLICATION_COMMAND_UPDATE,
}

export default intents